### ISSUE TITLE
Support request: interpreting results

### ISSUE THREAD

**Issue by alexweber** [openscanner/XGuardian#1]
First of all thanks for the great initiative!  I did a scan and found something but I'm not quite sure how to interpret and fix it: http://imgur.com/FsoZGLG

Thanks!

**Comment by wuyadong** [comment]
This means three applications have the authority of your id_rsa. I don't know what's the "bin" which is nerther Apple's nor assigned. You only need check the "bin" to make sure it is safe. You can open it on finder by the little finder button, remove it's authority by the delete button.
I'm on holiday at now, can't  do test or modify it. I will do more test and write some usage after about 3 days.
Thanks for your information.

**Comment by alexweber** [comment]
@wuyadong perfect, thank you!  I thought the delete button would actually remove the file and was hesitant about doing it.
